#!/bin/bash
pwd
0-current_working_directory
ls -a
chmod u+x 0-current_working_directory
git config user.email "saronkedir@gmail.com"
git config user.name "sari107"
git add .
git commit -m 'working directory'
git push
